name: Test Semaphore Kotlin Package

on:
    push:
        branches:
            - main

    pull_request:
        branches:
            - main
        types:
            - ready_for_review

    # Option to manually trigger the workflow
    workflow_dispatch:

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                  distribution: "temurin"
                  java-version: 17
            - name: Setup Android SDK
              uses: android-actions/setup-android@v2.0.10
            - name: Build android app
              run: ./gradlew build
            - name: Run tests
              uses: reactivecircus/android-emulator-runner@v2
              with:
                  api-level: 29
                  target: google_apis
                  arch: x86_64
                  disable-animations: true
                  emulator-options: "-no-snapshot -no-boot-anim -no-window -gpu swiftshader_indirect -memory 2048 -cores 1"
                  script: ./gradlew connectedAndroidTest
            - name: Upload test report
              if: failure()
              uses: actions/upload-artifact@v4
              with:
                  name: android-test-report
                  path: app/build/reports/androidTests/connected/debug/
